export const STORAGE_KEYS = {
  APPOINTMENTS: 'appointments',
  CUSTOMERS: 'customers',
  SERVICES: 'services',
  STOCK: 'stock',
  SALES: 'sales',
  SERVICE_SALES: 'serviceSales',
  CUSTOMER_RECORDS: 'customerRecords',
  PAYMENTS: 'payments',
  COSTS: 'costs',
  USERS: 'users',
  USER_PERFORMANCE: 'userPerformance',
  USER_ACTIVITIES: 'userActivities',
  STOCK_MOVEMENTS: 'stockMovements',
} as const;
